#version 430
layout(local_size_x = 1, local_size_y = 1) in;
layout(rgba32f, binding = 0) uniform image2D img_output;

void main() {
  ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    
  vec4 current_color = imageLoad(img_output, pixel_coords);  
  if (current_color.a > 0.01) {
      imageStore(img_output, pixel_coords, vec4(1, 0, 0, 1));
      return;
  }

  imageStore(img_output, pixel_coords, current_color);
}
